const data_champions = {
    "Aatrox": "Aatrox_0.jpg",
    "Ahri": "Ahri_0.jpg",
    "Alistar": "Alistar_0.jpg",
    "Ashe": "Ashe_0.jpg",
    "Blitzcrank": "Blitzcrank_0.jpg",
    "Braum": "braum.jpg",
    "Cho'Gath": "Chogath_0.jpg",
    "Dr. Mundo": "DrMundo_0.jpg",
    "Ezreal": "Ezreal_0.jpg",
    "Fizz": "Fizz_0.jpg",
    "Galio": "Galio_0.jpg",
    "Gragas": "Gragas_0.jpg",
    "Graves": "Graves_00_Base-Cigar.jpg",
    "Janna": "Janna_0.jpg",
    "Kai'sa": "Kaisa_0.jpg",
    "Karthus": "Karthus_0.jpg",
    "Kha'Zix": "Khazix_0.jpg",
    "Maokai": "Maokai_0.jpg",
    "Olaf": "Olaf_0.jpg",
    "Rammus": "Rammus_0.jpg",
    "Sivir": "Sivir_0.jpg",
    "Swain": "Swain_0.jpg",
    "Syndra": "Syndra_0.jpg",
    "Teemo": "Teemo_0.jpg",
    "Thresh": "Thresh_0.jpg",
    "Trundle": "Trundle_0.jpg",
    "Tryndamere": "Tryndamere_0.jpg",
    "Varus": "Varus_0.jpg",
    "Viktor": "Viktor_0.jpg",
    "Xin Zhao": "XinZhao_0.jpg",
    "Ziggs": "Ziggs_0.jpg",
};