const data_questionnaire = [
    {"type" : "question",                             "question" : "Que préférez-vous ?",                                            "propositions" : [["Être très résistant", 1],                                             ["Aider vos alliés", 2],                                           ["Faire des dégâts", 3],                 ["Être furtif", 4]]},
    {"type" : "question",                             "question" : "Que préférez-vous ?",                                            "propositions" : [["Être initiateur des combats", 5],                                     ["Agir seul", 6]]},
    {"type" : "question",                             "question" : "Comment voulez-vous les aider ?",                                "propositions" : [["Les protéger", 7],                                                    ["Les soigner", 8],                                                ["Contrôller les ennemis", 9]]},
    {"type" : "question",                             "question" : "Que préférez-vous ?",                                            "propositions" : [["La distance", 10],                                                    ["Le corps-à-corps", 11]]},
    {"type" : "question",                             "question" : "Voulez-vous être embêtant pour vos adversaires ?",               "propositions" : [["Oui", 12],                                                            ["Non", 13]]},
    {"type" : "question",                             "question" : "Voulez-vous absolument faire des dégâts significatifs ?",        "propositions" : [["Oui", 14],                                                            ["Non", 15]]},
    {"type" : "question",                             "question" : "Voulez-vous de la régénération ?",                               "propositions" : [["Oui", 16],                                                            ["Non", 17]]},
    {"type" : "question",                             "question" : "Voulez-vous pouvoir attraper vos adversaires ? ",                "propositions" : [["Oui", 18],                                                            ["Non", 19]]},
    {"type" : "question",                             "question" : "Que préférez-vous ?",                                            "propositions" : [["Être aggressif", 20],                                                 ["Jouer la sécurité", 21]]},
    {"type" : "question",                             "question" : "Que préférez-vous ?",                                            "propositions" : [["Pouvoir absorber les dégâts", 22],                                    ["Ennuyer les ennemis de loin", 23]]},
    {"type" : "question",                             "question" : "Que préférez-vous ?",                                            "propositions" : [["Les dégâts magiques", 24],                                            ["Les dégâts physiques", 25]]},
    {"type" : "question",                             "question" : "Que préférez-vous ?",                                            "propositions" : [["Les compétences", 26],                                                ["Les auto-attaques", 27]]},
    {"type" : "champion", "nom" : "Teemo"},
    {"type" : "question",                             "question" : "Que préférez-vous ?",                                            "propositions" : [["Les dégâts magiques", 28],                                            ["Les dégâts physiques", 29]]},
    {"type" : "question",                             "question" : "Voulez-vous de la régénération ?",                               "propositions" : [["Oui", 30],                                                            ["Non", 31]]},
    {"type" : "question",                             "question" : "Voulez-vous être rapide ?",                                      "propositions" : [["Oui", 32],                                                            ["Non", 33]]},
    {"type" : "champion", "nom" : "Dr. Mundo"},
    {"type" : "champion", "nom" : "Cho'Gath"},
    {"type" : "question",                             "question" : "Que préférez-vous ?",                                            "propositions" : [["Un champion difficile à jouer avec beaucoup de potentiel", 34],       ["Un champion simple à jouer avec peu de potentiel", 35]]},
    {"type" : "question",                             "question" : "Aimez-vous les combos",                                          "propositions" : [["Oui", 36],                                                            ["Non", 37]]},
    {"type" : "champion", "nom" : "Alistar"},
    {"type" : "champion", "nom" : "Janna"},
    {"type" : "question",                             "question" : "Voulez-vous pouvoir attraper vos adversaires ?",                 "propositions" : [["Oui", 38],                                                            ["Non", 19]]},
    {"type" : "question",                             "question" : "Aimez-vous les sorts difficile à toucher ?",                     "propositions" : [["Oui", 39],                                                            ["Non", 40]]},
    {"type" : "question",                             "question" : "Que préférez-vous ?",                                            "propositions" : [["Taper proche de votre cible", 41],                                    ["Taper loin de votre cible", 12]]},
    {"type" : "question",                             "question" : "Voulez-vous entraver vos adversaires ?",                         "propositions" : [["Oui", 42],                                                            ["Non", 43]]},
    {"type" : "question",                             "question" : "Que préférez-vous ?",                                            "propositions" : [["Être un assassin", 44],                                               ["Être un combattant", 45]]},
    {"type" : "question",                             "question" : "Aimez-vous les sorts difficile à toucher ?",                     "propositions" : [["Oui", 46],                                                            ["Non", 47]]},
    {"type" : "champion", "nom" : "Fizz"},
    {"type" : "champion", "nom" : "Kha'Zix"},
    {"type" : "champion", "nom" : "Maokai"},
    {"type" : "champion", "nom" : "Galio"},
    {"type" : "champion", "nom" : "Rammus"},
    {"type" : "question",                             "question" : "Préférez-vous les combos ou les boucliers ?",                    "propositions" : [["Les combos", 20],                                                     ["Les boucliers", 37]]},
    {"type" : "champion", "nom" : "Thresh"},
    {"type" : "question",                             "question" : "Voulez-vous faire beaucoup de dégâts ?",                         "propositions" : [["Oui", 48],                                                            ["Non", 49]]},
    {"type" : "question",                             "question" : "Voulez-vous soigner vos alliés ?",                               "propositions" : [["Oui", 20],                                                            ["Non", 31]]},
    {"type" : "champion", "nom" : "Braum"},
    {"type" : "question",                             "question" : "Que préférez-vous ?",                                            "propositions" : [["Un champion difficile à jouer avec beaucoup de potentiel", 34],       ["Un champion simple à jouer avec peu de potentiel", 35]]},
    {"type" : "question",                             "question" : "Dépendre de vos alliés vous dérange-t-il ?",                     "propositions" : [["Oui", 48],                                                            ["Non", 21]]},
    {"type" : "question",                             "question" : "Que préférez-vous ?",                                            "propositions" : [["Beaucoup de dégâts en peu de temps (burst)", 50],                     ["Peu de dégâts en beaucoup de temps (durée)", 51]]},
    {"type" : "question",                             "question" : "Voulez-vous être impactant sur toute la carte ?",                "propositions" : [["Oui", 52],                                                            ["Non", 53]]},
    {"type" : "question",                             "question" : "Que préférez-vous ?",                                            "propositions" : [["Taper de loin", 12],                                                  ["Taper de très loin", 54]]},
    {"type" : "question",                             "question" : "Voulez-vous beaucoup de mobilité ?",                             "propositions" : [["Oui", 55],                                                            ["Non", 56]]},
    {"type" : "question",                             "question" : "Que préférez-vous ?",                                            "propositions" : [["Les dégâts magiques", 57],                                            ["Les dégâts physiques", 29]]},
    {"type" : "question",                             "question" : "Voulez-vous de la régénération ?",                               "propositions" : [["Oui", 58],                                                            ["Non", 31]]},
    {"type" : "question",                             "question" : "Que préférez-vous ?",                                            "propositions" : [["Entraver l'adversaire", 59],                                          ["Être innarêtable", 60]]},
    {"type" : "question",                             "question" : "Que préférez-vous ?",                                            "propositions" : [["Être immortel pendant quelques secondes", 61],                        ["Être résistant très longtemps", 62]]},
    {"type" : "champion", "nom" : "Swain"},
    {"type" : "champion", "nom" : "Blitzcrank"},
    {"type" : "champion", "nom" : "Ahri"},
    {"type" : "champion", "nom" : "Viktor"},
    {"type" : "question",                             "question" : "Voulez-vous vous tenir à distance de vos adversaires ?",         "propositions" : [["Oui", 63],                                                            ["Non", 64]]},
    {"type" : "champion", "nom" : "Syndra"},
    {"type" : "question",                             "question" : "Aimez-vous les sorts difficiles à toucher ?",                    "propositions" : [["Oui", 65],                                                            ["Non", 66]]},
    {"type" : "question",                             "question" : "Que préférez-vous ?",                                            "propositions" : [["Taper de loin", 67],                                                  ["Taper de très loin", 68]]},
    {"type" : "question",                             "question" : "Que préférez-vous ?",                                            "propositions" : [["Taper relativement proche", 69],                                      ["Taper de loin", 70]]},
    {"type" : "question",                             "question" : "Voulez-vous des sorts difficiles à toucher ?",                   "propositions" : [["Oui", 28],                                                            ["Non", 71]]},
    {"type" : "champion", "nom" : "Aatrox"},
    {"type" : "champion", "nom" : "Trundle"},
    {"type" : "champion", "nom" : "Olaf"},
    {"type" : "champion", "nom" : "Tryndamere"},
    {"type" : "champion", "nom" : "Xin Zhao"},
    {"type" : "champion", "nom" : "Ziggs"},
    {"type" : "champion", "nom" : "Karthus"},
    {"type" : "champion", "nom" : "Varus"},
    {"type" : "champion", "nom" : "Ashe"},
    {"type" : "champion", "nom" : "Ezreal"},
    {"type" : "champion", "nom" : "Kai'sa"},
    {"type" : "champion", "nom" : "Graves"},
    {"type" : "champion", "nom" : "Sivir"},
    {"type" : "champion", "nom" : "Gragas"},
];