const data_champions = [
    {"nom" : "Aatrox",                   "img" : "Aatrox_0.png"},
    {"nom" : "Ahri",                     "img" : "Ahri_0.png"},
    {"nom" : "Alistar",                  "img" : "Alistar_0.png"},
    {"nom" : "Ashe",                     "img" : "Ashe_0.png"},
    {"nom" : "Blitzcrank",               "img" : "Blitzcrank_0.png"},
    {"nom" : "Braum",                    "img" : "braum.png"},
    {"nom" : "Cho'Gath",                 "img" : "Chogath_0.png"},
    {"nom" : "Dr. Mundo",                 "img" : "DrMundo_0.png"},
    {"nom" : "Ezreal",                   "img" : "Ezreal_0.png"},
    {"nom" : "Fizz",                     "img" : "Fizz_0.png"},
    {"nom" : "Galio",                    "img" : "Galio_0.png"},
    {"nom" : "Gragas",                   "img" : "Gragas_0.png"},
    {"nom" : "Graves",                   "img" : "Graves_00_Base-Cigar.png"},
    {"nom" : "Janna",                    "img" : "Janna_0.png"},
    {"nom" : "Kai'sa",                   "img" : "Kaisa_0.png"},
    {"nom" : "Karthus",                  "img" : "Karthus_0.png"},
    {"nom" : "Kha'Zix",                  "img" : "Khazix_0.png"},
    {"nom" : "Maokai",                   "img" : "Maokai_0.png"},
    {"nom" : "Olaf",                     "img" : "Olaf_0.png"},
    {"nom" : "Rammus",                   "img" : "Rammus_0.png"},
    {"nom" : "Sivir",                    "img" : "Sivir_0.png"},
    {"nom" : "Swain",                    "img" : "Swain_0.png"},
    {"nom" : "Syndra",                   "img" : "Syndra_0.png"},
    {"nom" : "Teemo",                    "img" : "Teemo_0.png"},
    {"nom" : "Thresh",                   "img" : "Thresh_0.png"},
    {"nom" : "Trundle",                  "img" : "Trundle_0.png"},
    {"nom" : "Tryndamere",               "img" : "Tryndamere_0.png"},
    {"nom" : "Varus",                    "img" : "Varus_0.png"},
    {"nom" : "Viktor",                   "img" : "Viktor_0.png"},
    {"nom" : "Xin Zhao",                 "img" : "XinZhao_0.png"},
    {"nom" : "Ziggs",                    "img" : "Ziggs_0.png"},
];